version: '3'
services:
  market_monitor_worker:
    build: .
    volumes:
      - .:/work
      - ./log:/log
    env_file:
      - docs/proj_env/env.list
    command: celery worker -A market_monitor -l info -n market_monitor -Q market_monitor -c 1
    networks:
      - app_net
  market_monitor_beat:
    build: .
    volumes:
      - .:/work
      - ./log:/log
    env_file:
      - docs/proj_env/env.list
    command: celery -A market_monitor beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    networks:
      - app_net
  market_monitor_server:
    build: .
    volumes:
      - .:/work
      - ./log:/log
    env_file:
      - docs/proj_env/env.list
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8003:8000
    deploy:
      restart_policy:
        condition: on-failure
      replicas: 1
    networks:
      - app_net
  market_monitor_flow:
    build: .
    volumes:
      - .:/work
      - ./log:/log
    env_file:
      - docs/proj_env/env.list
    command:  flower -A market_monitor --port=5555
    ports:
      - 5558:5555
    deploy:
      restart_policy:
        condition: on-failure
      replicas: 1
    networks:
      - app_net

networks:
  app_net:
    external: true
